version: '3'
services:
  kafka:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    hostname: kafka
    container_name: kafka


  ubirch-iota-service:
    image: ubirch/ubirch-iota-service
